version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: perpus-app
    container_name: perpus-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - /var/www/vendor
      - /var/www/public/build
      - /var/www/storage
      - /var/www/bootstrap/cache
    command: >
      sh -c "php artisan config:clear &&
             php artisan route:clear &&
             php artisan view:clear &&
             php-fpm"
    env_file:
      - .env
    networks:
      - perpus-network

  nginx:
    image: nginx:alpine
    container_name: perpus-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    depends_on:
      - app
    networks:
      - perpus-network

networks:
  perpus-network:
    driver: bridge
