version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: perpus-app
    container_name: perpus-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor-data:/var/www/vendor
      - public-build:/var/www/public/build
      - /var/www/storage
      - /var/www/bootstrap/cache
    env_file:
      - .env
    networks:
      - perpus-network

  nginx:
    image: nginx:alpine
    container_name: perpus-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - public-build:/var/www/public/build
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - perpus-network

volumes:
  vendor-data:
  public-build:


networks:
  perpus-network:
    driver: bridge
